//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnkaCMS.Core.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnkaCMS.Core.Globalization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama bulunamadı!.
        /// </summary>
        public static string DangerApplicationNotFound {
            get {
                return ResourceManager.GetString("DangerApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlişkili kayıt silinemez!.
        /// </summary>
        public static string DangerAssociatedRecordNotDeleted {
            get {
                return ResourceManager.GetString("DangerAssociatedRecordNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} daha önce kullanılmış!.
        /// </summary>
        public static string DangerFieldDuplicated {
            get {
                return ResourceManager.GetString("DangerFieldDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı boş bırakılamaz!.
        /// </summary>
        public static string DangerFieldIsEmpty {
            get {
                return ResourceManager.GetString("DangerFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanı {1} karakterden az girilmiş!.
        /// </summary>
        public static string DangerFieldLengthLimit {
            get {
                return ResourceManager.GetString("DangerFieldLengthLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimlik bilgileri bulunamadı!.
        /// </summary>
        public static string DangerIdentityUserNotFound {
            get {
                return ResourceManager.GetString("DangerIdentityUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifre hatalı!.
        /// </summary>
        public static string DangerIncorrectOldPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı şifre!.
        /// </summary>
        public static string DangerIncorrectPassword {
            get {
                return ResourceManager.GetString("DangerIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api client yetkili değil!.
        /// </summary>
        public static string DangerInvalidApiClient {
            get {
                return ResourceManager.GetString("DangerInvalidApiClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta adresi geçerli değil!.
        /// </summary>
        public static string DangerInvalidEmail {
            get {
                return ResourceManager.GetString("DangerInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik geçerli değil!.
        /// </summary>
        public static string DangerInvalidEntitiy {
            get {
                return ResourceManager.GetString("DangerInvalidEntitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 MB&apos;lık dosya boyutu kotasını aştınız!.
        /// </summary>
        public static string DangerInvalidFileSize1MB {
            get {
                return ResourceManager.GetString("DangerInvalidFileSize1MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre yeterince karmaşık değil!.
        /// </summary>
        public static string DangerInvalidPassword {
            get {
                return ResourceManager.GetString("DangerInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüklemek istediğiniz dosya &quot;.jpg&quot; ya da &quot;.png&quot; dosyası değil! .
        /// </summary>
        public static string DangerInvalidUploadJpgPng {
            get {
                return ResourceManager.GetString("DangerInvalidUploadJpgPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili kayıt onaylı değil!.
        /// </summary>
        public static string DangerItemNotApproved {
            get {
                return ResourceManager.GetString("DangerItemNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste boş!.
        /// </summary>
        public static string DangerListEmpty {
            get {
                return ResourceManager.GetString("DangerListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta gönderimi başarısız oldu!.
        /// </summary>
        public static string DangerMailDeliveryFailed {
            get {
                return ResourceManager.GetString("DangerMailDeliveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu işlem için yetkiniz yok!.
        /// </summary>
        public static string DangerNoPermission {
            get {
                return ResourceManager.GetString("DangerNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzgünüz böyle bir sayfa yok. Sayfa adresi yanlış yazılmış veya aradığınız sayfa yayından kaldırılmış olabilir. Şimdi anasayfaya yönlendiriliyorsunuz..
        /// </summary>
        public static string DangerPage404Message {
            get {
                return ResourceManager.GetString("DangerPage404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa bulunamadı!.
        /// </summary>
        public static string DangerPage404Title {
            get {
                return ResourceManager.GetString("DangerPage404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlanacak üst kayıt bulunamadı!.
        /// </summary>
        public static string DangerParentNotFound {
            get {
                return ResourceManager.GetString("DangerParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler aynı değil!.
        /// </summary>
        public static string DangerPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("DangerPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt bulunamadı!.
        /// </summary>
        public static string DangerRecordNotFound {
            get {
                return ResourceManager.GetString("DangerRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfada kayıt bulunamadı!.
        /// </summary>
        public static string DangerRecordNotFoundInPage {
            get {
                return ResourceManager.GetString("DangerRecordNotFoundInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik kodu uyuşmuyor!.
        /// </summary>
        public static string DangerSecurityCodesDoNotMatched {
            get {
                return ResourceManager.GetString("DangerSecurityCodesDoNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıt silinemez!.
        /// </summary>
        public static string DangerThisRecordCanNotDeleted {
            get {
                return ResourceManager.GetString("DangerThisRecordCanNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıya tanımlı bir rol bulunamadı!.
        /// </summary>
        public static string DangerUserHasNoRole {
            get {
                return ResourceManager.GetString("DangerUserHasNoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı!.
        /// </summary>
        public static string DangerUserNotFound {
            get {
                return ResourceManager.GetString("DangerUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kullanıcı adınızı giriniz..
        /// </summary>
        public static string EnterYourUsername {
            get {
                return ResourceManager.GetString("EnterYourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kullanıcı adınızı ve şifrenizi giriniz..
        /// </summary>
        public static string EnterYourUsernamePassword {
            get {
                return ResourceManager.GetString("EnterYourUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen formu doldurunuz..
        /// </summary>
        public static string FillForm {
            get {
                return ResourceManager.GetString("FillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi başarıyla tamamlandı..
        /// </summary>
        public static string InfoDeletionOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoDeletionOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla giriş yapıldı..
        /// </summary>
        public static string InfoLoginOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoLoginOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla çıkış yapıldı..
        /// </summary>
        public static string InfoLogoutOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoLogoutOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre başarıyla gönderildi..
        /// </summary>
        public static string InfoPasswordSentSuccesfully {
            get {
                return ResourceManager.GetString("InfoPasswordSentSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydetme işlemi başarıyla tamamlandı..
        /// </summary>
        public static string InfoSaveOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoSaveOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenleme işlemi başarılı..
        /// </summary>
        public static string InfoUpdateOperationSuccessful {
            get {
                return ResourceManager.GetString("InfoUpdateOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSure {
            get {
                return ResourceManager.GetString("QuestionAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilenleri onaylamak istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureApproveSelected {
            get {
                return ResourceManager.GetString("QuestionAreYouSureApproveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureDelete {
            get {
                return ResourceManager.GetString("QuestionAreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili olanları silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureDeleteSelected {
            get {
                return ResourceManager.GetString("QuestionAreYouSureDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumu sonlandırmak istediğinizden emin misiniz?.
        /// </summary>
        public static string QuestionAreYouSureLogout {
            get {
                return ResourceManager.GetString("QuestionAreYouSureLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adet seçildi..
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} alanına geçerli veri giriniz!.
        /// </summary>
        public static string WarnInvalidField {
            get {
                return ResourceManager.GetString("WarnInvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapmalı ya da kayıt olmalısınız!.
        /// </summary>
        public static string WarnLoginOrRegister {
            get {
                return ResourceManager.GetString("WarnLoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturum süresi doldu!.
        /// </summary>
        public static string WarnSessionTimeOut {
            get {
                return ResourceManager.GetString("WarnSessionTimeOut", resourceCulture);
            }
        }
    }
}
